# Generated by Django 2.2.8 on 2021-06-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_comments', '0002_parent'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE djangocms_comments_comment CONVERT TO CHARACTER SET utf8mb4;')
    ]
